export interface IBookInfo {
    title: string,
    year: string,
    subtitle: string,
    error: string,
    desc: string,
    authors: string,
    isbn10: string,
    isbn13: string,
    pages: string,
    url: string,
    price: 0,
    image: string,
    rating: string,
    publisher: string,
    language: string,
}